# Testlerden sonra bildirimi çalıştır
- name: Bildirim gönder (E-posta ve Slack)
  if: success()  # testler başarılı olursa çalışır
  run: |
    echo "🚀 Testler geçti, bildirimler gönderiliyor..."

    # ---- SLACK BİLDİRİMİ ----
    curl -X POST -H 'Content-type: application/json' \
      --data '{"text":"✅ *Tüm testler başarıyla geçti!* \n📦 Deploy işlemi başlatılıyor..."}' \
      ${{ secrets.SLACK_WEBHOOK_URL }}

    # ---- E-POSTA BİLDİRİMİ ----
    python - <<EOF
    import smtplib
    from email.mime.text import MIMEText

    msg = MIMEText("✅ Tüm testler başarıyla geçti!\n📦 Deploy işlemi başlatılıyor...")
    msg["Subject"] = "✅ Test Sonuçları - Başarılı"
    msg["From"] = "${{ secrets.EMAIL_USER }}"
    msg["To"] = "${{ secrets.EMAIL_USER }}"  # istersen farklı alıcı da ekleyebilirsin

    with smtplib.SMTP("${{ secrets.EMAIL_HOST }}", int("${{ secrets.EMAIL_PORT }}")) as server:
        server.starttls()
        server.login("${{ secrets.EMAIL_USER }}", "${{ secrets.EMAIL_PASS }}")
        server.send_message(msg)

    print("📨 E-posta bildirimi gönderildi!")
    EOF
